import * as v from 'valibot';
import { DecorTile } from '../../world/tiles';
import { Rarity } from '../rarity';
import type { DecorBlueprint } from './decor-blueprint';

const halloweenDecorExpiryDate = new Date('2025-11-07T01:00:00.000Z');

export const decorDex = {
  SmallRock: {
    tileRef: DecorTile.SmallRock,
    name: 'Small Garden Rock',
    coinPrice: 1_000,
    creditPrice: 2,
    rarity: Rarity.Common,
    baseTileScale: 1,
    isOneTimePurchase: false,
  },
  MediumRock: {
    tileRef: DecorTile.MediumRock,
    name: 'Medium Garden Rock',
    coinPrice: 2_500,
    creditPrice: 5,
    rarity: Rarity.Common,
    baseTileScale: 1,
    isOneTimePurchase: false,
  },
  LargeRock: {
    tileRef: DecorTile.LargeRock,
    name: 'Large Garden Rock',
    coinPrice: 5_000,
    creditPrice: 10,
    rarity: Rarity.Common,
    baseTileScale: 1,
    isOneTimePurchase: false,
  },
  HayBale: {
    tileRef: DecorTile.HayBale,
    rotationVariants: {
      90: {
        tileRef: DecorTile.HayBaleSideways,
        flipH: true,
      },
      180: {
        tileRef: DecorTile.HayBale,
        flipH: true,
      },
      270: {
        tileRef: DecorTile.HayBaleSideways,
      },
    },
    name: 'Hay Bale',
    coinPrice: 7_000,
    creditPrice: 12,
    rarity: Rarity.Common,
    baseTileScale: 1.8,
    isOneTimePurchase: false,
    nudgeY: -0.42,
  },
  SmallGravestone: {
    tileRef: DecorTile.SmallGravestone,
    rotationVariants: {
      90: {
        tileRef: DecorTile.SmallGravestoneSideways,
        flipH: true,
        baseTileScale: 1.12,
        nudgeY: -0.32,
      },
      180: {
        tileRef: DecorTile.SmallGravestone,
        flipH: true,
      },
      270: {
        tileRef: DecorTile.SmallGravestoneSideways,
        baseTileScale: 1.12,
        nudgeY: -0.32,
      },
    },
    name: 'Small Gravestone',
    coinPrice: 8_000,
    creditPrice: 12,
    rarity: Rarity.Common,
    baseTileScale: 1,
    isOneTimePurchase: false,
    nudgeY: -0.38,
    expiryDate: halloweenDecorExpiryDate,
  },
  WoodBench: {
    tileRef: DecorTile.WoodBench,
    rotationVariants: {
      90: {
        tileRef: DecorTile.WoodBenchSideways,
        flipH: true,
        baseTileScale: 1.46,
        nudgeY: -0.3,
      },
      180: {
        tileRef: DecorTile.WoodBenchBackwards,
      },
      270: {
        tileRef: DecorTile.WoodBenchSideways,
        baseTileScale: 1.46,
        nudgeY: -0.3,
      },
    },
    name: 'Wood Bench',
    coinPrice: 10_000,
    creditPrice: 15,
    rarity: Rarity.Common,
    baseTileScale: 1,
    isOneTimePurchase: false,
    nudgeY: -0.3,
    avatarNudgeY: -0.18,
  },
  WoodArch: {
    tileRef: DecorTile.WoodArch,
    rotationVariants: {
      90: {
        tileRef: DecorTile.WoodArchSide,
        flipH: true,
        baseTileScale: 2.1,
        nudgeY: -0.48,
      },
      180: {
        tileRef: DecorTile.WoodArch,
        flipH: true,
      },
      270: {
        tileRef: DecorTile.WoodArchSide,
        baseTileScale: 2.1,
        nudgeY: -0.48,
      },
    },
    name: 'Wood Arch',
    coinPrice: 20_000,
    creditPrice: 25,
    rarity: Rarity.Common,
    baseTileScale: 1.53,
    isOneTimePurchase: false,
    nudgeY: -0.5,
  },
  WoodBridge: {
    tileRef: DecorTile.WoodBridge,
    rotationVariants: {
      90: {
        tileRef: DecorTile.WoodBridgeSideways,
        flipH: true,
        baseTileScale: 1.7,
        nudgeY: -0.28,
      },
      180: {
        tileRef: DecorTile.WoodBridge,
        flipH: true,
      },
      270: {
        tileRef: DecorTile.WoodBridgeSideways,
        baseTileScale: 1.7,
        nudgeY: -0.28,
      },
    },
    name: 'Wood Bridge',
    coinPrice: 40_000,
    creditPrice: 35,
    rarity: Rarity.Common,
    baseTileScale: 1.22,
    isOneTimePurchase: false,
    nudgeY: -0.35,
    avatarNudgeY: -0.44,
  },
  WoodLampPost: {
    tileRef: DecorTile.WoodLampPost,
    name: 'Wood Lamp Post',
    coinPrice: 80_000,
    creditPrice: 49,
    rarity: Rarity.Common,
    baseTileScale: 1.5,
    isOneTimePurchase: false,
    nudgeY: -0.6,
  },
  WoodOwl: {
    tileRef: DecorTile.WoodOwl,
    name: 'Wood Owl',
    coinPrice: 90_000,
    creditPrice: 59,
    rarity: Rarity.Common,
    baseTileScale: 1.3,
    isOneTimePurchase: false,
    nudgeY: -0.4,
  },
  WoodBirdhouse: {
    tileRef: DecorTile.Birdhouse,
    name: 'Wood Birdhouse',
    coinPrice: 100_000,
    creditPrice: 69,
    rarity: Rarity.Common,
    baseTileScale: 1.5,
    isOneTimePurchase: false,
    nudgeY: -0.6,
  },
  WoodWindmill: {
    tileRef: DecorTile.WoodWindmill,
    name: 'Wood Windmill',
    coinPrice: 500_000,
    creditPrice: 74,
    rarity: Rarity.Common,
    baseTileScale: 1.5,
    isOneTimePurchase: false,
    nudgeY: -0.47,
  },
  MediumGravestone: {
    tileRef: DecorTile.MediumGravestone,
    rotationVariants: {
      90: {
        tileRef: DecorTile.MediumGravestoneSideways,
        flipH: true,
        baseTileScale: 1.32,
        nudgeY: -0.33,
      },
      180: {
        tileRef: DecorTile.MediumGravestone,
        flipH: true,
      },
      270: {
        tileRef: DecorTile.MediumGravestoneSideways,
        baseTileScale: 1.32,
        nudgeY: -0.33,
      },
    },
    name: 'Medium Gravestone',
    coinPrice: 500_000,
    creditPrice: 72,
    rarity: Rarity.Uncommon,
    baseTileScale: 1.2,
    isOneTimePurchase: false,
    nudgeY: -0.45,
    expiryDate: halloweenDecorExpiryDate,
  },
  StoneBench: {
    tileRef: DecorTile.StoneBench,
    rotationVariants: {
      90: {
        tileRef: DecorTile.StoneBenchSideways,
        flipH: true,
        baseTileScale: 1.47,
        nudgeY: -0.3,
      },
      180: {
        tileRef: DecorTile.StoneBench,
        flipH: true,
      },
      270: {
        tileRef: DecorTile.StoneBenchSideways,
        baseTileScale: 1.47,
        nudgeY: -0.3,
      },
    },
    name: 'Stone Bench',
    coinPrice: 1_000_000,
    creditPrice: 75,
    rarity: Rarity.Uncommon,
    baseTileScale: 1,
    isOneTimePurchase: false,
    nudgeY: -0.3,
    avatarNudgeY: -0.18,
  },
  StoneArch: {
    tileRef: DecorTile.StoneArch,
    rotationVariants: {
      90: {
        tileRef: DecorTile.StoneArchSideways,
        flipH: true,
        baseTileScale: 2.1,
        nudgeY: -0.44,
      },
      180: {
        tileRef: DecorTile.StoneArch,
        flipH: true,
      },
      270: {
        tileRef: DecorTile.StoneArchSideways,
        baseTileScale: 2.1,
        nudgeY: -0.44,
      },
    },
    name: 'Stone Arch',
    coinPrice: 4_000_000,
    creditPrice: 124,
    rarity: Rarity.Uncommon,
    baseTileScale: 1.53,
    isOneTimePurchase: false,
    nudgeY: -0.5,
  },
  StoneBridge: {
    tileRef: DecorTile.StoneBridge,
    rotationVariants: {
      90: {
        tileRef: DecorTile.StoneBridgeSideways,
        flipH: true,
        baseTileScale: 1.7,
        nudgeY: -0.28,
      },
      180: {
        tileRef: DecorTile.StoneBridge,
        flipH: true,
      },
      270: {
        tileRef: DecorTile.StoneBridgeSideways,
        baseTileScale: 1.7,
        nudgeY: -0.28,
      },
    },
    name: 'Stone Bridge',
    coinPrice: 5_000_000,
    creditPrice: 179,
    rarity: Rarity.Uncommon,
    baseTileScale: 1.22,
    isOneTimePurchase: false,
    nudgeY: -0.35,
    avatarNudgeY: -0.44,
  },
  StoneLampPost: {
    tileRef: DecorTile.StoneLampPost,
    name: 'Stone Lamp Post',
    coinPrice: 8_000_000,
    creditPrice: 199,
    rarity: Rarity.Uncommon,
    baseTileScale: 1.5,
    isOneTimePurchase: false,
    nudgeY: -0.6,
  },
  StoneGnome: {
    tileRef: DecorTile.StoneGnome,
    name: 'Stone Gnome',
    coinPrice: 9_000_000,
    creditPrice: 219,
    rarity: Rarity.Uncommon,
    baseTileScale: 1.3,
    isOneTimePurchase: false,
    nudgeY: -0.4,
  },
  StoneBirdbath: {
    tileRef: DecorTile.StoneBirdBath,
    name: 'Stone Birdbath',
    coinPrice: 10_000_000,
    creditPrice: 249,
    rarity: Rarity.Uncommon,
    baseTileScale: 1.2,
    isOneTimePurchase: false,
    nudgeY: -0.46,
  },
  LargeGravestone: {
    tileRef: DecorTile.LargeGravestone,
    rotationVariants: {
      90: {
        tileRef: DecorTile.LargeGravestoneSideways,
        flipH: true,
        nudgeY: -0.39,
        baseTileScale: 1.5,
      },
      180: {
        tileRef: DecorTile.LargeGravestone,
        flipH: true,
      },
      270: {
        tileRef: DecorTile.LargeGravestoneSideways,
        nudgeY: -0.39,
        baseTileScale: 1.5,
      },
    },
    name: 'Large Gravestone',
    coinPrice: 50_000_000,
    creditPrice: 299,
    rarity: Rarity.Rare,
    baseTileScale: 1.4,
    isOneTimePurchase: false,
    nudgeY: -0.51,
    expiryDate: halloweenDecorExpiryDate,
  },
  MarbleBench: {
    tileRef: DecorTile.MarbleBench,
    rotationVariants: {
      90: {
        tileRef: DecorTile.MarbleBenchSideways,
        flipH: true,
        baseTileScale: 1.55,
        nudgeY: -0.35,
      },
      180: {
        tileRef: DecorTile.MarbleBenchBackwards,
      },
      270: {
        tileRef: DecorTile.MarbleBenchSideways,
        baseTileScale: 1.55,
        nudgeY: -0.35,
      },
    },
    name: 'Marble Bench',
    coinPrice: 75_000_000,
    creditPrice: 329,
    rarity: Rarity.Rare,
    baseTileScale: 1,
    isOneTimePurchase: false,
    nudgeY: -0.3,
    avatarNudgeY: -0.18,
  },
  MarbleArch: {
    tileRef: DecorTile.MarbleArch,
    rotationVariants: {
      90: {
        tileRef: DecorTile.MarbleArchSideways,
        flipH: true,
        baseTileScale: 2.38,
        nudgeY: -0.57,
      },
      180: {
        tileRef: DecorTile.MarbleArch,
        flipH: true,
      },
      270: {
        tileRef: DecorTile.MarbleArchSideways,
        baseTileScale: 2.38,
        nudgeY: -0.57,
      },
    },
    name: 'Marble Arch',
    coinPrice: 100_000_000,
    creditPrice: 349,
    rarity: Rarity.Rare,
    baseTileScale: 1.53,
    isOneTimePurchase: false,
    nudgeY: -0.5,
  },
  MarbleBridge: {
    tileRef: DecorTile.MarbleBridge,
    rotationVariants: {
      90: {
        tileRef: DecorTile.MarbleBridgeSideways,
        flipH: true,
        baseTileScale: 1.7,
        nudgeY: -0.28,
      },
      180: {
        tileRef: DecorTile.MarbleBridge,
        flipH: true,
      },
      270: {
        tileRef: DecorTile.MarbleBridgeSideways,
        baseTileScale: 1.7,
        nudgeY: -0.28,
      },
    },
    name: 'Marble Bridge',
    coinPrice: 150_000_000,
    creditPrice: 379,
    rarity: Rarity.Rare,
    baseTileScale: 1.22,
    isOneTimePurchase: false,
    nudgeY: -0.35,
    avatarNudgeY: -0.44,
  },
  MarbleLampPost: {
    tileRef: DecorTile.MarbleLampPost,
    name: 'Marble Lamp Post',
    coinPrice: 200_000_000,
    creditPrice: 399,
    rarity: Rarity.Rare,
    baseTileScale: 1.5,
    isOneTimePurchase: false,
    nudgeY: -0.6,
  },
  MarbleBlobling: {
    tileRef: DecorTile.MarbleBlobling,
    name: 'Marble Blobling',
    coinPrice: 300_000_000,
    creditPrice: 429,
    rarity: Rarity.Rare,
    baseTileScale: 1.5,
    isOneTimePurchase: false,
    nudgeY: -0.56,
  },
  MarbleFountain: {
    tileRef: DecorTile.MarbleFountain,
    name: 'Marble Fountain',
    coinPrice: 450_000_000,
    creditPrice: 449,
    rarity: Rarity.Rare,
    baseTileScale: 1.5,
    isOneTimePurchase: false,
    nudgeY: -0.3,
  },
  MiniFairyCottage: {
    tileRef: DecorTile.MiniFairyCottage,
    name: 'Mini Fairy Cottage',
    coinPrice: 500_000_000,
    creditPrice: 549,
    rarity: Rarity.Rare,
    baseTileScale: 1.1,
    isOneTimePurchase: false,
    nudgeY: -0.37,
  },
  Cauldron: {
    tileRef: DecorTile.Cauldron,
    name: 'Cauldron',
    coinPrice: 666_000_000,
    creditPrice: 666,
    rarity: Rarity.Legendary,
    baseTileScale: 1.5,
    isOneTimePurchase: false,
    nudgeY: -0.25,
    expiryDate: halloweenDecorExpiryDate,
  },
  StrawScarecrow: {
    tileRef: DecorTile.StrawScarecrow,
    name: 'Straw Scarecrow',
    coinPrice: 1_000_000_000,
    creditPrice: 599,
    rarity: Rarity.Legendary,
    baseTileScale: 1.8,
    isOneTimePurchase: false,
    nudgeY: -0.65,
  },
  MiniFairyForge: {
    tileRef: DecorTile.MiniFairyForge,
    name: 'Mini Fairy Forge',
    coinPrice: 5_000_000_000,
    creditPrice: 979,
    rarity: Rarity.Legendary,
    baseTileScale: 1,
    isOneTimePurchase: false,
    nudgeY: -0.3,
  },
  MiniFairyKeep: {
    tileRef: DecorTile.MiniFairyKeep,
    name: 'Mini Fairy Keep',
    coinPrice: 25_000_000_000,
    creditPrice: 1249,
    rarity: Rarity.Mythic,
    baseTileScale: 1.05,
    isOneTimePurchase: false,
    nudgeY: -0.33,
  },
  MiniWizardTower: {
    tileRef: DecorTile.MiniWizardTower,
    name: 'Mini Wizard Tower',
    coinPrice: 75_000_000_000,
    creditPrice: 1379,
    rarity: Rarity.Mythic,
    baseTileScale: 1.8,
    isOneTimePurchase: false,
    nudgeY: -0.59,
  },
  PetHutch: {
    tileRef: DecorTile.PetHutch,
    name: 'Pet Hutch',
    coinPrice: 80_000_000_000,
    creditPrice: 499,
    rarity: Rarity.Divine,
    baseTileScale: 1.05,
    nudgeY: -0.45,
    isOneTimePurchase: true,
  },
} as const satisfies Record<Capitalize<string>, DecorBlueprint>;

export type DecorId = keyof typeof decorDex;
export const decorIds = Object.keys(decorDex) as DecorId[];
export const DecorIdSchema = v.picklist(decorIds);
export const decorEntries = Object.entries(decorDex) as Array<
  [DecorId, DecorBlueprint]
>;
