import { mapValues } from 'lodash';
import { Spritesheet, type TileRef } from './ref';

/**
 * Helper function to create a tile reference
 */
function createTileRef(spritesheet: Spritesheet, index: number): TileRef {
  return { type: 'tile', spritesheet, index };
}

/**
 * Helper function to create a set of tile references from a map of names to indices.
 * @param spritesheet The spritesheet to use for all tiles.
 * @param tiles A map of tile names to their indices in the spritesheet.
 * @returns An object with the same keys as `tiles`, where each value is a `TileRef`.
 */
function createTileSet<T extends Record<string, number>>(
  spritesheet: Spritesheet,
  tiles: T
) {
  return mapValues(tiles, (index) => createTileRef(spritesheet, index));
}

export const PlantsTile = createTileSet(Spritesheet.Plants, {
  Empty: 0,
  DirtPatch: 1,
  SproutFlower: 2,
  SproutVegetable: 3,
  SproutFruit: 4,
  SproutVine: 5,
  StemFlower: 6,
  Trellis: 7,
  Daffodil: 11,
  Tulip: 12,
  Sunflower: 13,
  Lily: 14,
  Starweaver: 15,
  Chrysanthemum: 16,
  Aloe: 18,
  Blueberry: 21,
  Banana: 22,
  Strawberry: 23,
  Mango: 24,
  Grape: 25,
  Watermelon: 26,
  Lemon: 27,
  Apple: 28,
  Pear: 29,
  Pineapple: 30,
  Pepper: 31,
  PalmTree: 3000,
  CacaoTree: 3001,
  Tree: 8,
  Tomato: 32,
  BabyCarrot: 33,
  Carrot: 34,
  Pumpkin: 35,
  Corn: 36,
  FavaBean: 37,
  Cacao: 38,
  PalmTreeTop: 39,
  BushyTree: 40,
  Coconut: 41,
  PassionFruit: 43,
  DragonFruit: 44,
  Lychee: 45,
  Mushroom: 3002,
  BurrosTail: 47,
  Echeveria: 49,
  Delphinium: 50,
  DawnCelestialCrop: 51,
  MoonCelestialCrop: 52,
  Camellia: 57,
  Hedge: 58,
  FlowerBush: 59,
  Squash: 60,
});

export const TallPlantsTile = createTileSet(Spritesheet.TallPlants, {
  Empty: 0,
  Bamboo: 1,
  DawnCelestialPlatform: 3,
  DawnCelestialPlant: 4,
  DawnCelestialPlantActive: 5,
  DawnCelestialPlatformTopmostLayer: 6,
  Cactus: 7,
  MoonCelestialPlatform: 9,
  MoonCelestialPlant: 10,
  MoonCelestialPlantActive: 11,
  StarweaverPlatform: 13,
  StarweaverPlant: 14,
});

export const SeedsTile = createTileSet(Spritesheet.Seeds, {
  Empty: 0,
  Daffodil: 1,
  Tulip: 2,
  Sunflower: 3,
  Starweaver: 6,
  DawnCelestial: 7,
  MoonCelestial: 8,
  Blueberry: 11,
  Banana: 12,
  Strawberry: 13,
  Mango: 14,
  Grape: 15,
  Watermelon: 16,
  Lemon: 17,
  Apple: 18,
  Pear: 19,
  Lily: 20,
  Pepper: 21,
  Tomato: 22,
  Carrot: 23,
  Pumpkin: 25,
  Corn: 26,
  Peach: 27,
  FavaBean: 28,
  Cacao: 29,
  Delphinium: 30,
  Coconut: 31,
  Mushroom: 32,
  PassionFruit: 33,
  DragonFruit: 34,
  Lychee: 35,
  BurrosTail: 37,
  Aloe: 39,
  Echeveria: 40,
  Bamboo: 41,
  Cactus: 42,
  Camellia: 48,
  Chrysanthemum: 49,
  Squash: 50,
});

export const ItemsTile = createTileSet(Spritesheet.Items, {
  // Empty: 0,
  // Coin: 1,
  Shovel: 2,
  // Dirt: 3,
  PlanterPot: 6,
  // InventoryBag: 7,
  WateringCan: 9,
  MoneyBag: 11,
  RainbowPotion: 14,
  GoldPotion: 15,
  WetPotion: 16,
  ChilledPotion: 17,
  FrozenPotion: 18,
  DawnlitPotion: 19,
  AmberlitPotion: 20,
  // JournalStamp: 22,
  // Donut: 23,
  // ToolsRestocked: 24,
  // SeedsRestocked: 25,
  // EggsRestocked: 26,
  // DecorRestocked: 27,
  // Leaderboard: 28,
  // Stats: 29,
  // ActivityLog: 30,
  // ChatBubble: 39,
  // ArrowKeys: 41,
  // Touchpad: 42,
});

export const SpecialPlantsTiles = createTileSet(Spritesheet.Animations, {
  MoonCelestialActivationTile: 91,
  DawnCelestialActivationTile: 92,
});

export const PetTiles = createTileSet(Spritesheet.Pets, {
  Bee: 1,
  Chicken: 2,
  Bunny: 3,
  Turtle: 4,
  Capybara: 5,
  Cow: 6,
  Pig: 7,
  Butterfly: 8,
  Snail: 9,
  Worm: 10,
  CommonEgg: 11,
  UncommonEgg: 12,
  RareEgg: 13,
  LegendaryEgg: 14,
  MythicalEgg: 15,
  DivineEgg: 16,
  CelestialEgg: 17,
  Squirrel: 18,
  Goat: 19,
  Dragonfly: 20,
  Turkey: 29,
  Peacock: 30,
});

export const MutationTiles = createTileSet(Spritesheet.Mutations, {
  Wet: 1,
  Chilled: 2,
  Frozen: 3,
  Puddle: 5,
  Dawnlit: 11,
  Amberlit: 12,
  Dawncharged: 13,
  Ambercharged: 14,
});

export const MutationOverlayTiles = createTileSet(
  Spritesheet.MutationOverlays,
  {
    WetTallPlant: 1,
    ChilledTallPlant: 2,
    FrozenTallPlant: 3,
    Wet: 4,
    Chilled: 5,
    Frozen: 6,
    Dawnlit: 7,
    Amberlit: 8,
    Dawncharged: 9,
    Ambercharged: 10,
  }
);

export const DecorTile = createTileSet(Spritesheet.Decor, {
  // Garden Rocks
  SmallRock: 11,
  MediumRock: 21,
  LargeRock: 31,
  // Wooden items
  WoodPedestal: 4,
  WoodBench: 13,
  WoodBenchBackwards: 14,
  WoodBenchSideways: 24,
  WoodBucketPedestal: 34,
  WoodLampPost: 23,
  WoodStool: 63,
  WoodArch: 33,
  WoodArchSide: 43,
  WoodBridge: 34,
  WoodBridgeSideways: 44,
  WoodOwl: 53,
  WoodGardenBox: 74,
  Birdhouse: 54,
  WoodWindmill: 64,
  // Stone items
  StonePedestal: 6,
  StoneBench: 15,
  StoneBenchSideways: 2600,
  StoneBucketPedestal: 16,
  StoneLampPost: 25,
  StoneColumn: 2601,
  StoneArch: 35,
  StoneArchSideways: 45,
  StoneBridge: 36,
  StoneBridgeSideways: 46,
  StoneGnome: 55,
  StoneGardenBox: 66,
  StoneBirdBath: 56,
  // Marble items
  MarblePedestal: 8,
  MarbleBench: 17,
  MarbleBenchBackwards: 18,
  MarbleBenchSideways: 28,
  MarbleBucketPedestal: 58,
  MarbleLampPost: 27,
  MarbleColumn: 68,
  MarbleArch: 37,
  MarbleArchSideways: 47,
  MarbleBridge: 38,
  MarbleBridgeSideways: 48,
  MarbleBlobling: 57,
  MarbleFountain: 58,
  MarbleGardenBox: 78,
  MiniFairyCottage: 50,
  MiniFairyForge: 40,
  MiniFairyKeep: 60,
  MiniWizardTower: 68,
  // Halloween items
  HayBale: 29,
  HayBaleSideways: 39,
  StrawScarecrow: 49,
  Cauldron: 59,
  SmallGravestone: 69,
  SmallGravestoneSideways: 70,
  MediumGravestone: 79,
  MediumGravestoneSideways: 80,
  LargeGravestone: 89,
  LargeGravestoneSideways: 90,
  // Pet items
  PetHutch: 30,
});
