import * as v from 'valibot';
import { PetTiles } from '../../world/tiles';
import { Rarity } from '../rarity';
import type { FaunaSpeciesBlueprint } from './fauna-blueprints';

export const faunaSpeciesDex = {
  Worm: {
    tileRef: PetTiles.Worm,
    name: 'Worm',
    coinsToFullyReplenishHunger: 500,
    innateAbilityWeights: {
      SeedFinderI: 50,
      ProduceEater: 50,
    },
    maxScale: 2.0,
    maturitySellPrice: 5_000,
    matureWeight: 0.1,
    moveProbability: 0.1,
    moveTweenDurationMs: 1346,
    hoursToMature: 12,
    rarity: Rarity.Common,
    tileTransformOrigin: 'bottom',
    nudgeY: -0.25,
    diet: ['Carrot', 'Strawberry', 'Aloe', 'Tomato', 'Apple'],
  },
  Snail: {
    tileRef: PetTiles.Snail,
    name: 'Snail',
    coinsToFullyReplenishHunger: 1_000,
    innateAbilityWeights: {
      CoinFinderI: 100,
    },
    maxScale: 2.0,
    maturitySellPrice: 10_000,
    matureWeight: 0.15,
    moveProbability: 0.01,
    moveTweenDurationMs: 1553,
    hoursToMature: 12,
    rarity: Rarity.Common,
    tileTransformOrigin: 'bottom',
    diet: ['Blueberry', 'Tomato', 'Corn', 'Daffodil', 'Chrysanthemum'],
    nudgeY: -0.25,
  },
  Bee: {
    tileRef: PetTiles.Bee,
    name: 'Bee',
    coinsToFullyReplenishHunger: 1_500,
    innateAbilityWeights: {
      ProduceScaleBoost: 50,
      ProduceMutationBoost: 50,
    },
    maxScale: 2.5,
    maturitySellPrice: 30_000,
    matureWeight: 0.2,
    moveProbability: 0.5,
    moveTweenDurationMs: 230,
    isFlying: true,
    hoursToMature: 12,
    rarity: Rarity.Common,
    diet: ['Strawberry', 'Blueberry', 'Daffodil', 'Lily', 'Chrysanthemum'],
  },
  Chicken: {
    tileRef: PetTiles.Chicken,
    name: 'Chicken',
    coinsToFullyReplenishHunger: 3_000,
    innateAbilityWeights: {
      EggGrowthBoost: 80,
      PetRefund: 20,
    },
    maxScale: 2.0,
    maturitySellPrice: 50_000,
    matureWeight: 3.0,
    moveProbability: 0.2,
    moveTweenDurationMs: 552,
    hoursToMature: 24,
    rarity: Rarity.Uncommon,
    tileTransformOrigin: 'bottom',
    nudgeY: -0.2,
    diet: ['Aloe', 'Corn', 'Watermelon', 'Pumpkin'],
  },
  Bunny: {
    tileRef: PetTiles.Bunny,
    name: 'Bunny',
    coinsToFullyReplenishHunger: 750,
    innateAbilityWeights: {
      CoinFinderII: 60,
      SellBoostI: 40,
    },
    maxScale: 2.0,
    maturitySellPrice: 75_000,
    matureWeight: 2.0,
    moveProbability: 0.3,
    moveTweenDurationMs: 403,
    hoursToMature: 24,
    rarity: Rarity.Uncommon,
    tileTransformOrigin: 'bottom',
    nudgeY: -0.2,
    diet: ['Carrot', 'Strawberry', 'Blueberry', 'OrangeTulip', 'Apple'],
  },
  Dragonfly: {
    tileRef: PetTiles.Dragonfly,
    name: 'Dragonfly',
    coinsToFullyReplenishHunger: 250,
    innateAbilityWeights: {
      HungerRestore: 70,
      PetMutationBoost: 30,
    },
    maxScale: 2.5,
    maturitySellPrice: 150_000,
    matureWeight: 0.2,
    moveProbability: 0.7,
    moveTweenDurationMs: 253,
    isFlying: true,
    hoursToMature: 24,
    rarity: Rarity.Uncommon,
    tileTransformOrigin: 'center',
    diet: ['Apple', 'OrangeTulip', 'Echeveria'],
  },
  Pig: {
    tileRef: PetTiles.Pig,
    name: 'Pig',
    coinsToFullyReplenishHunger: 50_000,
    innateAbilityWeights: {
      SellBoostII: 30,
      PetAgeBoost: 30,
      PetHatchSizeBoost: 30,
    },
    maxScale: 2.5,
    maturitySellPrice: 500_000,
    matureWeight: 200.0,
    moveProbability: 0.2,
    moveTweenDurationMs: 1484,
    hoursToMature: 72,
    rarity: Rarity.Rare,
    tileTransformOrigin: 'bottom',
    nudgeY: -0.15,
    diet: ['Watermelon', 'Pumpkin', 'Mushroom', 'Bamboo'],
  },
  Cow: {
    tileRef: PetTiles.Cow,
    name: 'Cow',
    coinsToFullyReplenishHunger: 25_000,
    innateAbilityWeights: {
      SeedFinderII: 30,
      HungerBoost: 30,
      PlantGrowthBoost: 30,
    },
    maxScale: 2.5,
    maturitySellPrice: 1_000_000,
    matureWeight: 600.0,
    moveProbability: 0.1,
    moveTweenDurationMs: 1840,
    hoursToMature: 72,
    rarity: Rarity.Rare,
    tileTransformOrigin: 'bottom',
    nudgeY: -0.15,
    diet: ['Coconut', 'Banana', 'BurrosTail', 'Mushroom'],
  },
  Turkey: {
    tileRef: PetTiles.Turkey,
    name: 'Turkey',
    coinsToFullyReplenishHunger: 500,
    innateAbilityWeights: {
      RainDance: 60,
      EggGrowthBoostII_NEW: 35,
      DoubleHatch: 5,
    },
    maxScale: 2.5,
    maturitySellPrice: 3_000_000,
    matureWeight: 10.0,
    moveProbability: 0.25,
    moveTweenDurationMs: 644,
    hoursToMature: 72,
    rarity: Rarity.Rare,
    tileTransformOrigin: 'bottom',
    nudgeY: -0.15,
    diet: ['FavaBean', 'Corn', 'Squash'],
  },
  Squirrel: {
    tileRef: PetTiles.Squirrel,
    name: 'Squirrel',
    coinsToFullyReplenishHunger: 15_000,
    innateAbilityWeights: {
      CoinFinderIII: 70,
      SellBoostIII: 20,
      PetMutationBoostII: 10,
    },
    maxScale: 2.0,
    maturitySellPrice: 5_000_000,
    matureWeight: 0.5,
    moveProbability: 0.4,
    moveTweenDurationMs: 357,
    hoursToMature: 100,
    rarity: Rarity.Legendary,
    tileTransformOrigin: 'bottom',
    nudgeY: -0.1,
    diet: ['Pumpkin', 'Banana', 'Grape'],
  },
  Turtle: {
    tileRef: PetTiles.Turtle,
    name: 'Turtle',
    coinsToFullyReplenishHunger: 100_000,
    innateAbilityWeights: {
      HungerRestoreII: 25,
      HungerBoostII: 25,
      PlantGrowthBoostII: 25,
      EggGrowthBoostII: 25,
    },
    maxScale: 2.5,
    maturitySellPrice: 10_000_000,
    matureWeight: 150.0,
    moveProbability: 0.05,
    moveTweenDurationMs: 1633,
    hoursToMature: 100,
    rarity: Rarity.Legendary,
    tileTransformOrigin: 'bottom',
    nudgeY: -0.15,
    diet: ['Watermelon', 'BurrosTail', 'Bamboo', 'Pepper'],
  },
  Goat: {
    tileRef: PetTiles.Goat,
    name: 'Goat',
    coinsToFullyReplenishHunger: 20_000,
    innateAbilityWeights: {
      PetHatchSizeBoostII: 10,
      PetAgeBoostII: 40,
      PetXpBoost: 40,
    },
    maxScale: 2.0,
    maturitySellPrice: 20_000_000,
    matureWeight: 100.0,
    moveProbability: 0.2,
    moveTweenDurationMs: 725,
    hoursToMature: 100,
    rarity: Rarity.Legendary,
    tileTransformOrigin: 'bottom',
    nudgeY: -0.1,
    diet: ['Pumpkin', 'Coconut', 'Pepper', 'Camellia', 'PassionFruit'],
  },
  Butterfly: {
    tileRef: PetTiles.Butterfly,
    name: 'Butterfly',
    coinsToFullyReplenishHunger: 25_000,
    innateAbilityWeights: {
      ProduceScaleBoostII: 40,
      ProduceMutationBoostII: 40,
      SeedFinderIII: 20,
    },
    maxScale: 2.5,
    maturitySellPrice: 50_000_000,
    matureWeight: 0.2,
    moveProbability: 0.6,
    moveTweenDurationMs: 288,
    isFlying: true,
    hoursToMature: 144,
    rarity: Rarity.Mythic,
    tileTransformOrigin: 'center',
    diet: ['Daffodil', 'Lily', 'Grape', 'Lemon', 'Sunflower'],
  },
  Peacock: {
    tileRef: PetTiles.Peacock,
    name: 'Peacock',
    coinsToFullyReplenishHunger: 100_000,
    innateAbilityWeights: {
      SellBoostIV: 40,
      PetXpBoostII: 50,
      PetRefundII: 10,
    },
    maxScale: 2.5,
    maturitySellPrice: 100_000_000,
    matureWeight: 5.0,
    moveProbability: 0.2,
    moveTweenDurationMs: 874,
    hoursToMature: 144,
    rarity: Rarity.Mythic,
    tileTransformOrigin: 'bottom',
    nudgeY: -0.1,
    diet: ['Cactus', 'Sunflower', 'Lychee'],
  },
  Capybara: {
    tileRef: PetTiles.Capybara,
    name: 'Capybara',
    coinsToFullyReplenishHunger: 150_000,
    innateAbilityWeights: {
      DoubleHarvest: 50,
      ProduceRefund: 50,
    },
    maxScale: 2.5,
    maturitySellPrice: 200_000_000,
    matureWeight: 50.0,
    moveProbability: 0.2,
    moveTweenDurationMs: 1150,
    hoursToMature: 144,
    rarity: Rarity.Mythic,
    tileTransformOrigin: 'bottom',
    nudgeY: -0.1,
    diet: ['Lemon', 'PassionFruit', 'DragonFruit', 'Lychee'],
  },
} as const satisfies Record<Capitalize<string>, FaunaSpeciesBlueprint>;

export type FaunaSpeciesId = keyof typeof faunaSpeciesDex;
export const faunaSpeciesIds = Object.keys(faunaSpeciesDex) as FaunaSpeciesId[];
export const FaunaSpeciesIdSchema = v.picklist(faunaSpeciesIds);
