import * as v from 'valibot';
import { PlantsTile, SeedsTile, TallPlantsTile } from '../../world/tiles';
import { Rarity } from '../rarity';
import { WeatherId } from '../weather';
import type { FloraSpeciesBlueprint } from './flora-blueprints';
import { HarvestType } from './HarvestType';

export const floraSpeciesDex = {
  Carrot: {
    seed: {
      tileRef: SeedsTile.Carrot,
      name: 'Carrot Seed',
      coinPrice: 10,
      creditPrice: 7,
      rarity: Rarity.Common,
    },
    plant: {
      tileRef: PlantsTile.BabyCarrot,
      name: 'Carrot Plant',
      harvestType: HarvestType.Single,
      baseTileScale: 0.7,
    },
    crop: {
      tileRef: PlantsTile.Carrot,
      name: 'Carrot',
      baseSellPrice: 20,
      baseWeight: 0.1,
      baseTileScale: 0.6,
      maxScale: 3,
    },
  },
  Strawberry: {
    seed: {
      tileRef: SeedsTile.Strawberry,
      name: 'Strawberry Seed',
      coinPrice: 50,
      creditPrice: 21,
      rarity: Rarity.Common,
    },
    plant: {
      tileRef: PlantsTile.SproutFruit,
      name: 'Strawberry Plant',
      harvestType: HarvestType.Multiple,
      // need to stagger their rate of starting to grow...
      slotOffsets: [
        { x: -0.2, y: -0.2, rotation: 0 },
        { x: 0.2, y: -0.25, rotation: 0 },
        { x: -0.18, y: 0.12, rotation: 0 },
        { x: 0.2, y: 0.05, rotation: 0 },
        { x: 0.01, y: -0.15, rotation: 0 },
      ],
      secondsToMature: 70,
      baseTileScale: 1,
      rotateSlotOffsetsRandomly: true,
    },
    crop: {
      tileRef: PlantsTile.Strawberry,
      name: 'Strawberry',
      baseSellPrice: 14,
      baseWeight: 0.05,
      baseTileScale: 0.25,
      maxScale: 2,
    },
  },
  Aloe: {
    seed: {
      tileRef: SeedsTile.Aloe,
      name: 'Aloe Seed',
      coinPrice: 135,
      creditPrice: 18,
      rarity: Rarity.Common,
    },
    plant: {
      tileRef: PlantsTile.Aloe,
      name: 'Aloe Plant',
      harvestType: HarvestType.Single,
      baseTileScale: 0.9,
    },
    crop: {
      tileRef: PlantsTile.Aloe,
      name: 'Aloe',
      baseSellPrice: 310,
      baseWeight: 1.5,
      baseTileScale: 0.7,
      maxScale: 2.5,
    },
  },
  FavaBean: {
    seed: {
      tileRef: SeedsTile.FavaBean,
      name: 'Fava Bean',
      coinPrice: 250,
      creditPrice: 30,
      rarity: Rarity.Uncommon,
    },
    plant: {
      tileRef: PlantsTile.SproutFlower,
      name: 'Fava Bean Plant',
      harvestType: HarvestType.Multiple,
      slotOffsets: [
        { x: -0.1, y: 0.15, rotation: 35 },
        { x: -0.23, y: 0.22, rotation: 35 },
        { x: 0.05, y: 0.3, rotation: 35 },
        { x: 0.18, y: 0.25, rotation: 35 },
        { x: 0.22, y: -0.02, rotation: 35 },
        { x: 0.1, y: -0.15, rotation: 35 },
        { x: -0.1, y: -0.17, rotation: 35 },
        { x: -0.25, y: -0.11, rotation: 35 },
      ],
      secondsToMature: 15 * 60,
      baseTileScale: 1.1,
      rotateSlotOffsetsRandomly: true,
    },
    crop: {
      tileRef: PlantsTile.FavaBean,
      name: 'Fava Bean Pod',
      baseSellPrice: 30,
      baseWeight: 0.03,
      baseTileScale: 0.3,
      maxScale: 3,
    },
  },
  Delphinium: {
    seed: {
      tileRef: SeedsTile.Delphinium,
      name: 'Delphinium Seed',
      coinPrice: 300,
      creditPrice: 12,
      rarity: Rarity.Uncommon,
    },
    plant: {
      tileRef: PlantsTile.Delphinium,
      name: 'Delphinium Plant',
      harvestType: HarvestType.Single,
      baseTileScale: 0.8,
      tileTransformOrigin: 'bottom',
      nudgeY: -0.43,
      nudgeYMultiplier: 0.05,
    },
    crop: {
      tileRef: PlantsTile.Delphinium,
      name: 'Delphinium',
      baseSellPrice: 530,
      baseWeight: 0.02,
      baseTileScale: 0.8,
      maxScale: 3,
    },
  },
  Blueberry: {
    seed: {
      tileRef: SeedsTile.Blueberry,
      name: 'Blueberry Seed',
      coinPrice: 400,
      creditPrice: 49,
      rarity: Rarity.Uncommon,
    },
    plant: {
      tileRef: PlantsTile.SproutFruit,
      name: 'Blueberry Plant',
      harvestType: HarvestType.Multiple,
      slotOffsets: [
        { x: -0.2, y: -0.2, rotation: 0 },
        { x: 0.175, y: -0.23, rotation: 0 },
        { x: -0.19, y: 0.12, rotation: 0 },
        { x: 0.21, y: 0.15, rotation: 0 },
        { x: 0.01, y: 0.0, rotation: 0 },
      ],
      secondsToMature: 105,
      baseTileScale: 1,
      rotateSlotOffsetsRandomly: true,
    },
    crop: {
      tileRef: PlantsTile.Blueberry,
      name: 'Blueberry',
      baseSellPrice: 23,
      baseWeight: 0.01,
      baseTileScale: 0.25,
      maxScale: 2,
    },
  },
  Apple: {
    seed: {
      tileRef: SeedsTile.Apple,
      name: 'Apple Seed',
      coinPrice: 500,
      creditPrice: 67,
      rarity: Rarity.Uncommon,
      unavailableSurfaces: ['discord'],
    },
    plant: {
      tileRef: PlantsTile.Tree,
      name: 'Apple Tree',
      harvestType: HarvestType.Multiple,
      // Slot offsets: y += 1 to compensate for baseTileScale removal
      slotOffsets: [
        { x: -0.35, y: -1.2, rotation: 0 },
        { x: -0.5, y: -0.8, rotation: 0 },
        { x: 0.1, y: -1.0, rotation: 0 },
        { x: -0.2, y: -0.45, rotation: 0 },
        { x: 0.55, y: -0.7, rotation: 0 },
        { x: 0.3, y: -0.5, rotation: 0 },
        { x: 0.4, y: 1.3, rotation: 0 },
      ],
      secondsToMature: 6 * 60 * 60,
      baseTileScale: 3,
      rotateSlotOffsetsRandomly: true,
      tileTransformOrigin: 'bottom',
      nudgeY: -0.25,
    },
    crop: {
      tileRef: PlantsTile.Apple,
      name: 'Apple',
      baseSellPrice: 73,
      baseWeight: 0.18,
      baseTileScale: 0.5,
      maxScale: 2,
    },
  },
  OrangeTulip: {
    // In fact, the tulip now appears as purpleish, but in the code it's still OrangeTulip
    seed: {
      tileRef: SeedsTile.Tulip,
      name: 'Tulip Seed',
      coinPrice: 600,
      creditPrice: 14,
      rarity: Rarity.Uncommon,
    },
    plant: {
      tileRef: PlantsTile.Tulip,
      name: 'Tulip Plant',
      harvestType: HarvestType.Single,
      baseTileScale: 0.5,
    },
    crop: {
      tileRef: PlantsTile.Tulip,
      name: 'Tulip',
      baseSellPrice: 767,
      baseWeight: 0.01,
      baseTileScale: 0.5,
      maxScale: 3,
    },
  },
  Tomato: {
    seed: {
      tileRef: SeedsTile.Tomato,
      name: 'Tomato Seed',
      coinPrice: 800,
      creditPrice: 79,
      rarity: Rarity.Uncommon,
    },
    plant: {
      tileRef: PlantsTile.SproutVine,
      name: 'Tomato Plant',
      harvestType: HarvestType.Multiple,
      slotOffsets: [
        { x: -0.3, y: -0.3, rotation: 0 },
        { x: 0.3, y: 0.3, rotation: 0 },
      ],
      secondsToMature: 11 * 100, // avi measured at growing 1% in 11 seconds
      baseTileScale: 1,
      rotateSlotOffsetsRandomly: true,
    },
    crop: {
      tileRef: PlantsTile.Tomato,
      name: 'Tomato',
      baseSellPrice: 27,
      baseWeight: 0.3,
      baseTileScale: 0.33,
      maxScale: 2,
    },
  },
  Daffodil: {
    seed: {
      tileRef: SeedsTile.Daffodil,
      name: 'Daffodil Seed',
      coinPrice: 1000,
      creditPrice: 19,
      rarity: Rarity.Rare,
    },
    plant: {
      tileRef: PlantsTile.Daffodil,
      name: 'Daffodil Plant',
      harvestType: HarvestType.Single,
      baseTileScale: 0.5,
    },
    crop: {
      tileRef: PlantsTile.Daffodil,
      name: 'Daffodil',
      baseSellPrice: 1090,
      baseWeight: 0.01,
      baseTileScale: 0.5,
      maxScale: 3,
    },
  },
  Corn: {
    seed: {
      tileRef: SeedsTile.Corn,
      name: 'Corn Kernel',
      coinPrice: 1300,
      creditPrice: 135,
      rarity: Rarity.Rare,
    },
    plant: {
      tileRef: PlantsTile.SproutVegetable,
      name: 'Corn Plant',
      harvestType: HarvestType.Multiple,
      slotOffsets: [{ x: 0, y: -0.1, rotation: 0 }],
      secondsToMature: 130, // avi measured growing 10% in 13 seconds
      baseTileScale: 1,
      rotateSlotOffsetsRandomly: false,
    },
    crop: {
      tileRef: PlantsTile.Corn,
      name: 'Corn',
      baseSellPrice: 36,
      baseWeight: 1.2,
      baseTileScale: 0.7,
      maxScale: 2,
    },
  },
  Watermelon: {
    seed: {
      tileRef: SeedsTile.Watermelon,
      name: 'Watermelon Seed',
      coinPrice: 2500,
      creditPrice: 195,
      rarity: Rarity.Rare,
    },
    plant: {
      tileRef: PlantsTile.Watermelon,
      name: 'Watermelon Plant',
      harvestType: HarvestType.Single,
      baseTileScale: 0.8,
    },
    crop: {
      tileRef: PlantsTile.Watermelon,
      name: 'Watermelon',
      baseSellPrice: 2708,
      baseWeight: 4.5,
      baseTileScale: 0.8,
      maxScale: 3,
    },
  },
  Pumpkin: {
    seed: {
      tileRef: SeedsTile.Pumpkin,
      name: 'Pumpkin Seed',
      coinPrice: 3000,
      creditPrice: 210,
      rarity: Rarity.Rare,
    },
    plant: {
      tileRef: PlantsTile.Pumpkin,
      name: 'Pumpkin Plant',
      harvestType: HarvestType.Single,
      baseTileScale: 0.8,
    },
    crop: {
      tileRef: PlantsTile.Pumpkin,
      name: 'Pumpkin',
      baseSellPrice: 3700,
      baseWeight: 6,
      baseTileScale: 0.8,
      maxScale: 3,
    },
  },
  Echeveria: {
    seed: {
      tileRef: SeedsTile.Echeveria,
      name: 'Echeveria Cutting',
      coinPrice: 4200,
      creditPrice: 113,
      rarity: Rarity.Rare,
    },
    plant: {
      tileRef: PlantsTile.Echeveria,
      name: 'Echeveria Plant',
      harvestType: HarvestType.Single,
      baseTileScale: 0.8,
    },
    crop: {
      tileRef: PlantsTile.Echeveria,
      name: 'Echeveria',
      baseSellPrice: 4600,
      baseWeight: 0.8,
      baseTileScale: 0.8,
      maxScale: 2.75,
    },
  },
  Coconut: {
    seed: {
      tileRef: SeedsTile.Coconut,
      name: 'Coconut Seed',
      coinPrice: 6000,
      creditPrice: 235,
      rarity: Rarity.Legendary,
    },
    plant: {
      tileRef: PlantsTile.PalmTree,
      name: 'Coconut Tree',
      harvestType: HarvestType.Multiple,
      // Slot offsets: y += 1.35 to compensate for baseTileScale removal
      slotOffsets: [
        { x: -0.2, y: -1.25, rotation: 0 },
        { x: -0.3, y: -1.05, rotation: 0 },
        { x: 0.2, y: -1.15, rotation: 0 },
        { x: -0.25, y: -0.75, rotation: 0 },
        { x: 0, y: -0.95, rotation: 0 },
        { x: 0.3, y: -0.85, rotation: 0 },
        { x: 0.05, y: -0.65, rotation: 0 },
      ],
      secondsToMature: 12 * 60 * 60,
      baseTileScale: 3,
      rotateSlotOffsetsRandomly: true,
      tileTransformOrigin: 'bottom',
      nudgeY: -0.35,
    },
    crop: {
      tileRef: PlantsTile.Coconut,
      name: 'Coconut',
      baseSellPrice: 302,
      baseWeight: 5,
      baseTileScale: 0.25,
      maxScale: 3,
    },
  },
  Banana: {
    seed: {
      tileRef: SeedsTile.Banana,
      name: 'Banana Seed',
      coinPrice: 7500,
      creditPrice: 199,
      rarity: Rarity.Legendary,
      getCanSpawnInGuild: (guildId) => {
        const lastChar = guildId.slice(-1);
        const lastCharNum = parseInt(lastChar, 10);
        return !Number.isNaN(lastCharNum) && lastCharNum % 2 === 0;
      },
      unavailableSurfaces: ['web'],
    },
    plant: {
      tileRef: PlantsTile.PalmTree,
      name: 'Banana Plant',
      harvestType: HarvestType.Multiple,
      // Slot offsets: y += 1.0 to compensate for baseTileScale removal
      slotOffsets: [
        { x: -0.3, y: -0.7, rotation: -90 + 100 },
        { x: -0.2, y: -0.7, rotation: -90 + 80 },
        { x: -0.1, y: -0.7, rotation: -90 + 60 },
        { x: 0, y: -0.7, rotation: -90 + 40 },
        { x: 0.1, y: -0.7, rotation: -90 + 20 },
      ],
      secondsToMature: 4 * 60 * 60, // 4 hours
      baseTileScale: 2.5,
      rotateSlotOffsetsRandomly: false,
      tileTransformOrigin: 'bottom',
      nudgeY: -0.4,
    },
    crop: {
      tileRef: PlantsTile.Banana,
      name: 'Banana',
      baseSellPrice: 1750,
      baseWeight: 0.12,
      baseTileScale: 0.5,
      maxScale: 1.7,
    },
  },
  Lily: {
    seed: {
      tileRef: SeedsTile.Lily,
      name: 'Lily Seed',
      coinPrice: 20_000,
      creditPrice: 34,
      rarity: Rarity.Legendary,
    },
    plant: {
      tileRef: PlantsTile.Lily,
      name: 'Lily Plant',
      harvestType: HarvestType.Single,
      baseTileScale: 0.75,
      nudgeY: -0.1,
    },
    crop: {
      tileRef: PlantsTile.Lily,
      name: 'Lily',
      baseSellPrice: 20123,
      baseWeight: 0.02,
      baseTileScale: 0.5,
      maxScale: 2.75,
    },
  },
  Camellia: {
    seed: {
      tileRef: SeedsTile.Camellia,
      name: 'Camellia Seed',
      coinPrice: 55_000,
      creditPrice: 289,
      rarity: Rarity.Legendary,
    },
    plant: {
      tileRef: PlantsTile.Hedge,
      name: 'Camellia Hedge',
      harvestType: HarvestType.Multiple,
      // Slot offsets: y += 0.4 to compensate for baseTileScale removal
      slotOffsets: [
        // Top triangle (3 slots at the top)
        { x: 0, y: -0.5, rotation: 0 },
        { x: -0.28, y: -0.2, rotation: 0 },
        { x: 0.28, y: -0.2, rotation: 0 },
        // The rest below (5 slots)
        { x: -0.35, y: 0.2, rotation: 0 },
        { x: 0.32, y: 0.2, rotation: 0 },
        { x: -0.3, y: 0.65, rotation: 0 },
        { x: 0.28, y: 0.65, rotation: 0 },
        { x: 0, y: 0.4, rotation: 0 },
      ],
      secondsToMature: 24 * 60 * 60,
      baseTileScale: 2,
      nudgeY: -0.4,
      tileTransformOrigin: 'bottom',
      nudgeYMultiplier: 0.5,
      rotateSlotOffsetsRandomly: true,
    },
    crop: {
      tileRef: PlantsTile.Camellia,
      name: 'Camellia',
      baseSellPrice: 4_875,
      baseWeight: 0.3,
      baseTileScale: 0.4,
      maxScale: 2.5,
    },
  },
  Squash: {
    seed: {
      tileRef: SeedsTile.Squash,
      name: 'Squash Seed',
      coinPrice: 55_000,
      creditPrice: 199,
      rarity: Rarity.Legendary,
    },
    plant: {
      tileRef: PlantsTile.SproutFlower,
      name: 'Squash Plant',
      harvestType: HarvestType.Multiple,
      // Slot offsets: y += 0.12 to compensate for baseTileScale removal
      slotOffsets: [
        { x: -0.08, y: 0.32, rotation: 35 },
        { x: 0.2, y: 0.12, rotation: 35 },
        { x: -0.2, y: 0.02, rotation: 35 },
      ],
      secondsToMature: 25 * 60,
      baseTileScale: 1.2,
      rotateSlotOffsetsRandomly: true,
    },
    crop: {
      tileRef: PlantsTile.Squash,
      name: 'Squash',
      baseSellPrice: 3_500,
      baseWeight: 0.3,
      baseTileScale: 0.4,
      maxScale: 2.5,
    },
  },
  BurrosTail: {
    seed: {
      tileRef: SeedsTile.BurrosTail,
      name: "Burro's Tail Cutting",
      coinPrice: 93_000,
      creditPrice: 338,
      rarity: Rarity.Legendary,
    },
    plant: {
      tileRef: PlantsTile.Trellis,
      name: "Burro's Tail Plant",
      harvestType: HarvestType.Multiple,
      // Slot offsets: y += -0.12 to compensate for baseTileScale removal
      slotOffsets: [
        { x: -0.13, y: -0.22, rotation: 0 },
        { x: 0.17, y: 0.01, rotation: 0 },
      ],
      secondsToMature: 30 * 60, // 30 minutes
      baseTileScale: 0.8,
      rotateSlotOffsetsRandomly: false,
    },
    crop: {
      tileRef: PlantsTile.BurrosTail,
      name: "Burro's Tail",
      baseSellPrice: 6_000,
      baseWeight: 0.4,
      baseTileScale: 0.4,
      maxScale: 2.5,
    },
  },
  Mushroom: {
    seed: {
      tileRef: SeedsTile.Mushroom,
      name: 'Mushroom Spore',
      coinPrice: 150_000,
      creditPrice: 249,
      rarity: Rarity.Mythic,
    },
    plant: {
      tileRef: PlantsTile.Mushroom,
      name: 'Mushroom Plant',
      harvestType: HarvestType.Single,
      baseTileScale: 0.55,
    },
    crop: {
      tileRef: PlantsTile.Mushroom,
      name: 'Mushroom',
      baseSellPrice: 160_000,
      baseWeight: 25,
      baseTileScale: 0.65,
      maxScale: 3.5,
    },
  },
  Cactus: {
    seed: {
      tileRef: SeedsTile.Cactus,
      name: 'Cactus Seed',
      coinPrice: 250_000,
      creditPrice: 250,
      rarity: Rarity.Mythic,
    },
    plant: {
      tileRef: TallPlantsTile.Cactus,
      name: 'Cactus Plant',
      harvestType: HarvestType.Single,
      baseTileScale: 2.5,
      tileTransformOrigin: 'bottom',
      nudgeY: -0.4,
      nudgeYMultiplier: 0.3,
    },
    crop: {
      tileRef: TallPlantsTile.Cactus,
      name: 'Cactus',
      baseSellPrice: 261_000,
      baseWeight: 1500,
      baseTileScale: 2.5,
      maxScale: 1.8,
    },
  },
  Bamboo: {
    seed: {
      tileRef: SeedsTile.Bamboo,
      name: 'Bamboo Seed',
      coinPrice: 400_000,
      creditPrice: 300,
      rarity: Rarity.Mythic,
    },
    plant: {
      tileRef: TallPlantsTile.Bamboo,
      name: 'Bamboo Plant',
      harvestType: HarvestType.Single,
      baseTileScale: 2.5,
      tileTransformOrigin: 'bottom',
      nudgeY: -0.45,
      nudgeYMultiplier: 0.3,
    },
    crop: {
      tileRef: TallPlantsTile.Bamboo,
      name: 'Bamboo Shoot',
      baseSellPrice: 500_000,
      baseWeight: 1,
      baseTileScale: 2.5,
      maxScale: 2,
    },
  },
  Chrysanthemum: {
    seed: {
      tileRef: SeedsTile.Chrysanthemum,
      name: 'Chrysanthemum Seed',
      coinPrice: 670_000,
      creditPrice: 567,
      rarity: Rarity.Mythic,
    },
    plant: {
      tileRef: PlantsTile.FlowerBush,
      name: 'Chrysanthemum Bush',
      harvestType: HarvestType.Multiple,
      slotOffsets: [
        { x: 0, y: 0, rotation: 0 },
        { x: -0.28, y: 0.22, rotation: 0 },
        { x: 0.28, y: 0.22, rotation: 0 },
        { x: 0, y: 0.33, rotation: 0 },
        { x: -0.25, y: -0.2, rotation: 0 },
        { x: 0.25, y: -0.2, rotation: 0 },
        { x: 0, y: -0.28, rotation: 0 },
      ],
      secondsToMature: 24 * 60 * 60, // 24 hours
      baseTileScale: 1,
      rotateSlotOffsetsRandomly: false,
    },
    crop: {
      tileRef: PlantsTile.Chrysanthemum,
      name: 'Chrysanthemum',
      baseSellPrice: 18_000,
      baseWeight: 0.01,
      baseTileScale: 0.3,
      maxScale: 2.75,
    },
  },
  Grape: {
    seed: {
      tileRef: SeedsTile.Grape,
      name: 'Grape Seed',
      coinPrice: 850_000,
      creditPrice: 599,
      rarity: Rarity.Mythic,
      getCanSpawnInGuild: (guildId) => guildId.endsWith('1'),
      unavailableSurfaces: ['web'],
    },
    plant: {
      tileRef: PlantsTile.SproutVine,
      name: 'Grape Plant',
      harvestType: HarvestType.Multiple,
      slotOffsets: [{ x: 0, y: 0, rotation: 0 }],
      secondsToMature: 24 * 60 * 60, // 24 hours
      baseTileScale: 1,
      rotateSlotOffsetsRandomly: true,
    },
    crop: {
      tileRef: PlantsTile.Grape,
      name: 'Grape',
      baseSellPrice: 12_500,
      baseWeight: 3,
      baseTileScale: 0.5,
      maxScale: 2,
    },
  },
  Pepper: {
    seed: {
      tileRef: SeedsTile.Pepper,
      name: 'Pepper Seed',
      coinPrice: 1_000_000,
      creditPrice: 629,
      rarity: Rarity.Divine,
    },
    plant: {
      tileRef: PlantsTile.SproutVine,
      name: 'Pepper Plant',
      harvestType: HarvestType.Multiple,
      slotOffsets: [
        { x: 0.03, y: 0.219, rotation: 0 },
        { x: 0.272, y: 0.122, rotation: 0 },
        { x: -0.122, y: 0.137, rotation: 0 },
        { x: 0.218, y: -0.045, rotation: 0 },
        { x: -0.032, y: -0.047, rotation: 0 },
        { x: -0.157, y: -0.2, rotation: 0 },
        { x: 0.23, y: -0.23, rotation: 0 },
        { x: -0.223, y: -0.25, rotation: 0 },
        { x: 0.05, y: -0.35, rotation: 0 },
      ],
      secondsToMature: 560, // avi measured growing 10% in 56 seconds
      baseTileScale: 1,
      rotateSlotOffsetsRandomly: true,
    },
    crop: {
      tileRef: PlantsTile.Pepper,
      name: 'Pepper',
      baseSellPrice: 7220,
      baseWeight: 0.5,
      baseTileScale: 0.3,
      maxScale: 2,
    },
  },
  Lemon: {
    seed: {
      tileRef: SeedsTile.Lemon,
      name: 'Lemon Seed',
      coinPrice: 2_000_000,
      creditPrice: 500,
      rarity: Rarity.Divine,
      getCanSpawnInGuild: (guildId) => guildId.endsWith('2'),
      unavailableSurfaces: ['web'],
    },
    plant: {
      tileRef: PlantsTile.Tree,
      name: 'Lemon Tree',
      harvestType: HarvestType.Multiple,
      // Slot offsets: y += 0.8 to compensate for baseTileScale removal
      slotOffsets: [
        { x: -0.5, y: -0.7, rotation: 0 },
        { x: 0.4, y: -0.8, rotation: 0 },
        { x: -0.3, y: -0.38, rotation: 0 },
        { x: 0.2, y: -0.4, rotation: 0 },
        { x: 0.01, y: -0.7, rotation: 0 },
        { x: -0.05, y: -1.0, rotation: 0 },
      ],
      secondsToMature: 12 * 60 * 60,
      baseTileScale: 2.3,
      rotateSlotOffsetsRandomly: true,
      tileTransformOrigin: 'bottom',
      nudgeY: -0.25,
    },
    crop: {
      tileRef: PlantsTile.Lemon,
      name: 'Lemon',
      baseSellPrice: 10_000,
      baseWeight: 0.5,
      baseTileScale: 0.25,
      maxScale: 3,
    },
  },
  PassionFruit: {
    seed: {
      tileRef: SeedsTile.PassionFruit,
      name: 'Passion Fruit Seed',
      coinPrice: 2_750_000,
      creditPrice: 679,
      rarity: Rarity.Divine,
    },
    plant: {
      tileRef: PlantsTile.SproutVine,
      name: 'Passion Fruit Plant',
      harvestType: HarvestType.Multiple,
      // Slot offsets: y += 0.06 to compensate for baseTileScale removal
      slotOffsets: [
        { x: -0.3, y: -0.24, rotation: -10 },
        { x: 0.3, y: 0.36, rotation: 10 },
      ],
      secondsToMature: 24 * 60 * 60,
      baseTileScale: 1.1,
      rotateSlotOffsetsRandomly: true,
    },
    crop: {
      tileRef: PlantsTile.PassionFruit,
      name: 'Passion Fruit',
      baseSellPrice: 24_500,
      baseWeight: 9.5,
      baseTileScale: 0.35,
      maxScale: 2,
    },
  },
  DragonFruit: {
    seed: {
      tileRef: SeedsTile.DragonFruit,
      name: 'Dragon Fruit Seed',
      coinPrice: 5_000_000,
      creditPrice: 715,
      rarity: Rarity.Divine,
    },
    plant: {
      tileRef: PlantsTile.PalmTreeTop,
      name: 'Dragon Fruit Plant',
      harvestType: HarvestType.Multiple,
      // Slot offsets: y += 0.36 to compensate for baseTileScale removal
      slotOffsets: [
        { x: -0.33, y: -0.14, rotation: 0 },
        { x: -0.1, y: -0.31, rotation: 0 },
        { x: 0.36, y: -0.16, rotation: 0 },
        { x: -0.25, y: 0.26, rotation: 0 },
        { x: 0, y: -0.1, rotation: 0 },
        { x: 0.4, y: 0.16, rotation: 0 },
        { x: 0.1, y: 0.26, rotation: 0 },
      ],
      secondsToMature: 600,
      baseTileScale: 1.6,
      rotateSlotOffsetsRandomly: true,
    },
    crop: {
      tileRef: PlantsTile.DragonFruit,
      name: 'Dragon Fruit',
      baseSellPrice: 24_500,
      baseWeight: 8.4,
      baseTileScale: 0.4,
      maxScale: 2,
    },
  },
  Cacao: {
    seed: {
      tileRef: SeedsTile.Cacao,
      name: 'Cacao Bean',
      coinPrice: 10_000_000,
      creditPrice: 750,
      rarity: Rarity.Divine,
    },
    plant: {
      tileRef: PlantsTile.CacaoTree,
      name: 'Cacao Plant',
      harvestType: HarvestType.Multiple,
      slotOffsets: [
        { x: 0.28, y: -0.37, rotation: 20 },
        { x: -0.3, y: -0.27, rotation: 20 },
        { x: -0.05, y: -0.62, rotation: 20 },
        { x: 0.45, y: -0.87, rotation: 20 },
        { x: -0.5, y: -0.77, rotation: 20 },
        { x: -0.05, y: -0.07, rotation: 20 },
      ],
      secondsToMature: 24 * 60 * 60,
      baseTileScale: 2.8,
      rotateSlotOffsetsRandomly: true,
      tileTransformOrigin: 'bottom',
      nudgeY: -0.32,
    },
    crop: {
      tileRef: PlantsTile.Cacao,
      name: 'Cacao Fruit',
      baseSellPrice: 70_000,
      baseWeight: 0.5,
      baseTileScale: 0.4,
      maxScale: 2.5,
    },
  },
  Lychee: {
    seed: {
      tileRef: SeedsTile.Lychee,
      name: 'Lychee Pit',
      coinPrice: 25_000_000,
      creditPrice: 819,
      rarity: Rarity.Divine,
      getCanSpawnInGuild: (guildId) => guildId.endsWith('2'),
      unavailableSurfaces: ['web'],
    },
    plant: {
      tileRef: PlantsTile.BushyTree,
      name: 'Lychee Plant',
      harvestType: HarvestType.Multiple,
      // Slot offsets: y += 0.12 to compensate for baseTileScale removal
      slotOffsets: [
        { x: -0.4, y: -0.12, rotation: 0 },
        { x: 0.3, y: -0.18, rotation: 0 },
        { x: -0.2, y: 0.24, rotation: 0 },
        { x: 0.2, y: 0.22, rotation: 0 },
        { x: 0.01, y: -0.35, rotation: 0 },
        { x: -0.05, y: -0.07, rotation: 0 },
      ],
      secondsToMature: 24 * 60 * 60,
      baseTileScale: 1.2,
      rotateSlotOffsetsRandomly: true,
    },
    crop: {
      tileRef: PlantsTile.Lychee,
      name: 'Lychee Fruit',
      baseSellPrice: 50_000,
      baseWeight: 9,
      baseTileScale: 0.2,
      maxScale: 2,
    },
  },
  Sunflower: {
    seed: {
      tileRef: SeedsTile.Sunflower,
      name: 'Sunflower Seed',
      coinPrice: 100_000_000,
      creditPrice: 900,
      rarity: Rarity.Divine,
    },
    plant: {
      tileRef: PlantsTile.StemFlower,
      name: 'Sunflower Plant',
      harvestType: HarvestType.Multiple,
      slotOffsets: [{ x: -0.01, y: -0.33, rotation: 0 }],
      secondsToMature: 24 * 60 * 60,
      rotateSlotOffsetsRandomly: false,
      tileTransformOrigin: 'bottom',
      baseTileScale: 0.8,
      nudgeY: -0.35,
    },
    crop: {
      tileRef: PlantsTile.Sunflower,
      name: 'Sunflower',
      baseSellPrice: 750_000,
      baseWeight: 10,
      baseTileScale: 0.5,
      maxScale: 2.5,
    },
  },
  Starweaver: {
    seed: {
      tileRef: SeedsTile.Starweaver,
      name: 'Starweaver Pod',
      coinPrice: 1_000_000_000,
      creditPrice: 1000,
      rarity: Rarity.Celestial,
    },
    plant: {
      tileRef: TallPlantsTile.StarweaverPlant,
      name: 'Starweaver Plant',
      harvestType: HarvestType.Multiple,
      // Slot offsets: y += 0.3 to compensate for baseTileScale removal
      slotOffsets: [{ x: 0.004, y: -0.308, rotation: 0 }],
      secondsToMature: 24 * 60 * 60,
      baseTileScale: 1.5,
      rotateSlotOffsetsRandomly: false,
      nudgeY: -0.27,
      tileTransformOrigin: 'bottom',
      immatureTileRef: TallPlantsTile.StarweaverPlatform,
      isFixedScale: true,
      // growingAnimationTiles: {
      //   frames: 10,
      //   row: 8,
      //   fps: 20,
      //   nudgeY: -0.2,
      // },
    },
    crop: {
      tileRef: PlantsTile.Starweaver,
      name: 'Starweaver Fruit',
      baseSellPrice: 10_000_000,
      baseWeight: 10,
      baseTileScale: 0.6,
      maxScale: 2,
    },
  },
  DawnCelestial: {
    seed: {
      tileRef: SeedsTile.DawnCelestial,
      name: 'Dawnbinder Pod',
      coinPrice: 10_000_000_000,
      creditPrice: 1129,
      rarity: Rarity.Celestial,
    },
    plant: {
      tileRef: TallPlantsTile.DawnCelestialPlant,
      name: 'Dawnbinder',
      harvestType: HarvestType.Multiple,
      secondsToMature: 24 * 60 * 60,
      // Slot offsets: y += 0.78 to compensate for baseTileScale removal
      slotOffsets: [{ x: -0.015, y: -0.53, rotation: 0 }],
      baseTileScale: 2.3,
      rotateSlotOffsetsRandomly: false,
      tileTransformOrigin: 'bottom',
      nudgeY: -0.2,
      abilities: ['DawnKisser'],
      activeState: {
        tileRef: TallPlantsTile.DawnCelestialPlantActive,
        weatherRequirement: WeatherId.Dawn,
        // activeAnimationTiles: {
        //   frames: 10,
        //   row: 6,
        //   fps: 20,
        //   nudgeY: -0.1,
        // },
      },
      topmostLayerTileRef: TallPlantsTile.DawnCelestialPlatformTopmostLayer,
      immatureTileRef: TallPlantsTile.DawnCelestialPlatform,
      isFixedScale: true,
      // growingAnimationTiles: {
      //   frames: 10,
      //   row: 8,
      //   fps: 20,
      //   nudgeY: -0.2,
      // },
    },
    crop: {
      tileRef: PlantsTile.DawnCelestialCrop,
      name: 'Dawnbinder Bulb',
      baseSellPrice: 11_000_000,
      baseWeight: 6,
      baseTileScale: 0.4,
      maxScale: 2.5,
      transformOrigin: 'top',
    },
  },
  MoonCelestial: {
    seed: {
      tileRef: SeedsTile.MoonCelestial,
      name: 'Moonbinder Pod',
      coinPrice: 50_000_000_000,
      creditPrice: 1249,
      rarity: Rarity.Celestial,
    },
    plant: {
      tileRef: TallPlantsTile.MoonCelestialPlant,
      name: 'Moonbinder',
      harvestType: HarvestType.Multiple,
      // Slot offsets: y += 0.9 to compensate for baseTileScale removal
      slotOffsets: [
        { x: 0.01, y: -0.38, rotation: 0 },
        { x: -0.26, y: 0.58, rotation: -30 },
        { x: 0.23, y: 0.42, rotation: 20 },
      ],
      secondsToMature: 24 * 60 * 60,
      baseTileScale: 2.5,
      rotateSlotOffsetsRandomly: false,
      tileTransformOrigin: 'bottom',
      nudgeY: -0.2,
      abilities: ['MoonKisser'],
      activeState: {
        tileRef: TallPlantsTile.MoonCelestialPlantActive,
        weatherRequirement: WeatherId.AmberMoon,
        // activeAnimationTiles: {
        //   frames: 10,
        //   row: 6,
        //   fps: 20,
        //   nudgeY: -0.1,
        // },
      },
      immatureTileRef: TallPlantsTile.MoonCelestialPlatform,
      isFixedScale: true,
      // growingAnimationTiles: {
      //   frames: 10,
      //   row: 8,
      //   fps: 20,
      //   nudgeY: -0.2,
      // },
    },
    crop: {
      tileRef: PlantsTile.MoonCelestialCrop,
      name: 'Moonbinder Bulb',
      baseSellPrice: 11_000_000,
      baseWeight: 2,
      baseTileScale: 0.4,
      maxScale: 2,
      transformOrigin: 'bottom',
    },
  },
} as const satisfies Record<Capitalize<string>, FloraSpeciesBlueprint>;

export type FloraSpeciesId = keyof typeof floraSpeciesDex;
export const floraSpeciesIds = Object.keys(floraSpeciesDex) as FloraSpeciesId[];
export const floraSpeciesEntries = Object.entries(floraSpeciesDex) as Array<
  [FloraSpeciesId, FloraSpeciesBlueprint]
>;
export const FloraSpeciesIdSchema = v.picklist(floraSpeciesIds);
